// flow-typed signature: 59796f418774ea28c5ac15d4967fa3d5
// flow-typed version: <<STUB>>/merge-stream_v^1.0.1/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'merge-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'merge-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'merge-stream/index' {
  declare module.exports: $Exports<'merge-stream'>;
}
declare module 'merge-stream/index.js' {
  declare module.exports: $Exports<'merge-stream'>;
}
