// flow-typed signature: ebd3c128ba54b412ae4b3b807b090dce
// flow-typed version: <<STUB>>/postcss-all-unset_v^1.1.0/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-all-unset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-all-unset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-all-unset/lib/rules-fabric' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-all-unset/index' {
  declare module.exports: $Exports<'postcss-all-unset'>;
}
declare module 'postcss-all-unset/index.js' {
  declare module.exports: $Exports<'postcss-all-unset'>;
}
declare module 'postcss-all-unset/lib/rules-fabric.js' {
  declare module.exports: $Exports<'postcss-all-unset/lib/rules-fabric'>;
}
