// flow-typed signature: 4cfd948132b177333b93604fcf0fb301
// flow-typed version: <<STUB>>/postcss-sassy-import_v^1.2.3/flow_v0.37.4

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-sassy-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-sassy-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-sassy-import/lib/fs-util' {
  declare module.exports: any;
}

declare module 'postcss-sassy-import/lib/glob' {
  declare module.exports: any;
}

declare module 'postcss-sassy-import/lib/to-scss' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-sassy-import/index' {
  declare module.exports: $Exports<'postcss-sassy-import'>;
}
declare module 'postcss-sassy-import/index.js' {
  declare module.exports: $Exports<'postcss-sassy-import'>;
}
declare module 'postcss-sassy-import/lib/fs-util.js' {
  declare module.exports: $Exports<'postcss-sassy-import/lib/fs-util'>;
}
declare module 'postcss-sassy-import/lib/glob.js' {
  declare module.exports: $Exports<'postcss-sassy-import/lib/glob'>;
}
declare module 'postcss-sassy-import/lib/to-scss.js' {
  declare module.exports: $Exports<'postcss-sassy-import/lib/to-scss'>;
}
